# Generated by Django 4.1 on 2022-10-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_task_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_url',
            field=models.URLField(default='https://cdn.discordapp.com/attachments/1027273502060982372/1027407971828908032/ToDoicon.png'),
            preserve_default=False,
        ),
    ]
